### ISSUE TITLE
tower-hedge tests fail on master

### ISSUE THREAD

**Issue by olix0r** [tower-rs/tower#284]
```
#; doe ~/b/rs/tower  (master ✔)
:; cargo test -p tower-hedge
   Compiling tower-hedge v0.1.0 (/Users/ver/b/rs/tower/tower-hedge)
    Finished dev [unoptimized + debuginfo] target(s) in 4.47s
     Running target/debug/deps/tower_hedge-e0dfa047bf723c13

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/hedge-a44175868860e33c

running 5 tests
test hedge_hedge_completes_first ... FAILED
test completes_before_hedge ... FAILED
test hedge_orig_completes_first ... FAILED
test request_not_clonable ... FAILED
test request_not_retyable ... FAILED

failures:

---- hedge_hedge_completes_first stdout ----
thread 'hedge_hedge_completes_first' panicked at 'service not ready; poll_ready must be called first', tower-test/src/mock/mod.rs:131:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- completes_before_hedge stdout ----
thread 'completes_before_hedge' panicked at 'service not ready; poll_ready must be called first', tower-test/src/mock/mod.rs:131:13

---- hedge_orig_completes_first stdout ----
thread 'hedge_orig_completes_first' panicked at 'service not ready; poll_ready must be called first', tower-test/src/mock/mod.rs:131:13

---- request_not_clonable stdout ----
thread 'request_not_clonable' panicked at 'service not ready; poll_ready must be called first', tower-test/src/mock/mod.rs:131:13

---- request_not_retyable stdout ----
thread 'request_not_retyable' panicked at 'service not ready; poll_ready must be called first', tower-test/src/mock/mod.rs:131:13


failures:
    completes_before_hedge
    hedge_hedge_completes_first
    hedge_orig_completes_first
    request_not_clonable
    request_not_retyable

test result: FAILED. 0 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p tower-hedge --test hedge'
```

It does not appear that this module is included in CI.

cc @adleong

**Comment by adleong** [comment]
Fixed by #287
